name: shop_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  dio: ^5.4.0
  firebase_auth: ^4.17.2
  firebase_core: ^2.25.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  get: ^4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.1.0
  google_sign_in: ^6.2.1
  http: ^1.2.0
  rive: ^0.12.4
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  sizer: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/vectors/
    - assets/rive/
  fonts:
    - family: trika
      fonts:
        - asset: assets/fonts/trika_regular.ttf
        - asset: assets/fonts/trika_bold.ttf
          weight: 700
    - family: abdElrady
      fonts:
        - asset: assets/fonts/abd_elrady_regular.otf
        - asset: assets/fonts/abd_elrady_bold.otf
          weight: 700
