// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNTZswhuC-OJduomKdiMbIUXbXnSloyTQ',
    appId: '1:581857654688:android:c6dcce7a6db39f36bb96c5',
    messagingSenderId: '581857654688',
    projectId: 'furnoture-shop',
    storageBucket: 'furnoture-shop.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWC5SHgX8E6DQxYPIKRd5BCf8gqZfs5rQ',
    appId: '1:285445477987:ios:4027e04f30226affbb0a56',
    messagingSenderId: '285445477987',
    projectId: 'shop-app-2024',
    storageBucket: 'shop-app-2024.appspot.com',
    iosBundleId: 'com.example.shopApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqp6ZquQPcfc4rq2YQMrCFC_GLjNBAXW8',
    appId: '1:581857654688:web:bae7e7e4ad559e35bb96c5',
    messagingSenderId: '581857654688',
    projectId: 'furnoture-shop',
    authDomain: 'furnoture-shop.firebaseapp.com',
    storageBucket: 'furnoture-shop.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqp6ZquQPcfc4rq2YQMrCFC_GLjNBAXW8',
    appId: '1:581857654688:web:3eea35dac2f77cfabb96c5',
    messagingSenderId: '581857654688',
    projectId: 'furnoture-shop',
    authDomain: 'furnoture-shop.firebaseapp.com',
    storageBucket: 'furnoture-shop.firebasestorage.app',
  );

}